### ISSUE TITLE
uninitialized constant Playwright::ChannelOwners::WebSocket (NameError)

### ISSUE THREAD

**Issue by goldenking0412** [YusukeIwaki/playwright-ruby-client#109]
## STEP TO REPRODUCE

```
page.goto('https://www.websocket.org/echo.html')
page.click('#connect')
```

---

```
#<Thread:0x00007f342403ce60@/home/user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/playwright-ruby-client-0.6.3/lib/playwright/transport.rb:53 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	5: from /home/user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/playwright-ruby-client-0.6.3/lib/playwright/transport.rb:53:in `block in async_run'
	4: from /home/user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/playwright-ruby-client-0.6.3/lib/playwright/transport.rb:71:in `handle_stdout'
	3: from /home/user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/playwright-ruby-client-0.6.3/lib/playwright/connection.rb:13:in `block in initialize'
	2: from /home/user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/playwright-ruby-client-0.6.3/lib/playwright/connection.rb:126:in `dispatch'
	1: from /home/user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/playwright-ruby-client-0.6.3/lib/playwright/connection.rb:202:in `create_remote_object'
/home/user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/playwright-ruby-client-0.6.3/lib/playwright/connection.rb:202:in `const_get': uninitialized constant Playwright::ChannelOwners::WebSocket (NameError)
Did you mean?  Playwright::WebSocket
               Webpacker
	5: from /home/user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/playwright-ruby-client-0.6.3/lib/playwright/transport.rb:53:in `block in async_run'
	4: from /home/user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/playwright-ruby-client-0.6.3/lib/playwright/transport.rb:71:in `handle_stdout'
	3: from /home/user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/playwright-ruby-client-0.6.3/lib/playwright/connection.rb:13:in `block in initialize'
	2: from /home/user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/playwright-ruby-client-0.6.3/lib/playwright/connection.rb:126:in `dispatch'
	1: from /home/user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/playwright-ruby-client-0.6.3/lib/playwright/connection.rb:201:in `create_remote_object'
/home/user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/playwright-ruby-client-0.6.3/lib/playwright/connection.rb:209:in `rescue in create_remote_object': Missing type WebSocket (RuntimeError)
```

Here's new issue I am getting recently

**Comment by YusukeIwaki** [comment]
Sorry for inconvenience.
playwright-ruby-client 0.6.6 fixes this issue.
