### ISSUE TITLE
Error with Rails and Spring: Playwright::Error: Error: stack[60].file: expected string, got object

### ISSUE THREAD

**Issue by YusukeIwaki** [YusukeIwaki/playwright-ruby-client#185]
### Step To Reproduce / Observed behavior

Found in https://github.com/YusukeIwaki/capybara-playwright-driver/issues/46
Caused by #168 (from v1.15.beta2)

Prepare Rails application with Spring enabled.
Then launch rails console and paste the code below:

```
require 'playwright'
Playwright.create(playwright_cli_executable_path: './node_modules/.bin/playwright') do |playwright|
  playwright.chromium.launch(headless: false) do |browser|
    page = browser.new_page
    page.goto('https://google.com')
  end
end
```

```
SEND>{:id=>3, :guid=>"browser-type@35aa768ca4f2bc303905cfc166d1594d", :method=>"launch", :params=>{:headless=>false}}
RECV>{"id"=>3, "error"=>{"error"=>{"message"=>"stack[60].file: expected string, got object", "stack"=>"Error: stack[60].file: expected string, got object\n    at tString (/Users/yusuke-iwaki/Desktop/railsfeature/node_modules/playwright-core/lib/protocol/validatorPrimitives.js:48:9)\n    at /Users/yusuke-iwaki/Desktop/railsfeature/node_modules/playwright-core/lib/protocol/validatorPrimitives.js:99:21\n    at /Users/yusuke-iwaki/Desktop/railsfeature/node_modules/playwright-core/lib/protocol/validator.js:45:14\n    at /Users/yusuke-iwaki/Desktop/railsfeature/node_modules/playwright-core/lib/protocol/validatorPrimitives.js:86:34\n    at Array.map (<anonymous>)\n    at /Users/yusuke-iwaki/Desktop/railsfeature/node_modules/playwright-core/lib/protocol/validatorPrimitives.js:86:16\n    at /Users/yusuke-iwaki/Desktop/railsfeature/node_modules/playwright-core/lib/protocol/validatorPrimitives.js:77:12\n    at /Users/yusuke-iwaki/Desktop/railsfeature/node_modules/playwright-core/lib/protocol/validatorPrimitives.js:99:21\n    at /Users/yusuke-iwaki/Desktop/railsfeature/node_modules/playwright-core/lib/protocol/validatorPrimitives.js:77:12\n    at DispatcherConnection._validateMetadata (/Users/yusuke-iwaki/Desktop/railsfeature/node_modules/playwright-core/lib/dispatchers/dispatcher.js:227:69)", "name"=>"Error"}}}
Playwright::Error: Error: stack[60].file: expected string, got object
from /Users/yusuke-iwaki/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/promises.rb:1257:in `wait_until_resolved!'
```

### Expected behavior

Showing google.com

**Comment by YusukeIwaki** [comment]
```
    private def with_logging(&block)
      locations = caller_locations
      first_api_call_location_idx = locations.index { |loc| loc.absolute_path.include?('playwright_api') }
      unless first_api_call_location_idx
        return block.call(nil)
      end

      locations = locations.slice(first_api_call_location_idx..-1)

      api_call_location = locations.shift

      api_class = File.basename(api_call_location.absolute_path, '.rb')
      api_method = api_call_location.label
      api_name = "#{api_class}##{api_method}"

      stacks = locations
      stacks.each_with_index do |stack, i|
        puts "#{i} ::: #{stack.absolute_path}"
      end
```

It seems the absolute_path of the last stack is `nil` when spring is enabled.

```
48 ::: /Users/yusuke-iwaki/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb
49 ::: /Users/yusuke-iwaki/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb
50 ::: /Users/yusuke-iwaki/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb
51 ::: /Users/yusuke-iwaki/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb
52 ::: /Users/yusuke-iwaki/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application/boot.rb
53 ::: <internal:/Users/yusuke-iwaki/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>
54 ::: <internal:/Users/yusuke-iwaki/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>
55 ::: 
```

**Comment by YusukeIwaki** [comment]
```
/Users/yusuke-iwaki/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
/Users/yusuke-iwaki/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
/Users/yusuke-iwaki/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
<internal:/Users/yusuke-iwaki/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/Users/yusuke-iwaki/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
-e:1:in `<main>'
```

main
