### ISSUE TITLE
1.18.2 以降を Windows Ruby 2.7 で動かすと `wrong exec option symbol: pgroup (ArgumentError)` が発生する

### ISSUE THREAD

**Issue by owayo** [YusukeIwaki/playwright-ruby-client#200]
### Step To Reproduce / Observed behavior
https://github.com/owayo/playwright-demo

```
require 'bundler/setup'
require 'playwright'

LAUNCH_PARAMS = {
  headless: false, 
  channel: 'chrome', ignoreDefaultArgs: ['--enable-automation']
}.freeze

Playwright.create(playwright_cli_executable_path: './node_modules/.bin/playwright') do |playwright|
  playwright.chromium.launch_persistent_context("./chrome/", **LAUNCH_PARAMS) do |browser|
    browser.new_page.goto("https://www.google.co.jp/")
    sleep 5
  end
end
```

エラー内容
```
Traceback (most recent call last):
        6: from main.rb:14:in `<main>'
        5: from D:/msys64/mingw64/lib/ruby/gems/2.7.0/gems/playwright-ruby-client-1.19.0/lib/playwright.rb:66:in `create'
        4: from D:/msys64/mingw64/lib/ruby/gems/2.7.0/gems/playwright-ruby-client-1.19.0/lib/playwright/connection.rb:36:in `async_run'
        3: from D:/msys64/mingw64/lib/ruby/gems/2.7.0/gems/playwright-ruby-client-1.19.0/lib/playwright/transport.rb:49:in `async_run'
        2: from D:/msys64/mingw64/lib/ruby/2.7.0/open3.rb:101:in `popen3'
        1: from D:/msys64/mingw64/lib/ruby/2.7.0/open3.rb:213:in `popen_run'
D:/msys64/mingw64/lib/ruby/2.7.0/open3.rb:213:in `spawn': wrong exec option symbol: pgroup (ArgumentError)
```

### Expected behavior
エラーが発生しないこと

### Environment
playwright 1.19.0
playwright-ruby-client 1.19.0
(1.18では問題なく動作)
Paste the output of `ruby --version`
以下の2バージョンでエラーになることを確認
```
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x64-mingw32]
```

```
ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x64-mingw32]
```
MacのRubyではエラーが発生しない
```
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
```

こちらのコミットによるものだと思われます
[690501317c0b310c54ebeec05e4a1b59d8665b91](https://github.com/YusukeIwaki/playwright-ruby-client/commit/690501317c0b310c54ebeec05e4a1b59d8665b91)

**Comment by YusukeIwaki** [comment]
@owayo  ご丁寧にご報告いただき、ありがとうございます。
v1.19.1, v1.18.3にて修正対応しました。

**Comment by owayo** [comment]
スピーディな修正ありがとうございます。
ありがたく使わせていただきます。
