### ISSUE TITLE
Playwright Android doesn't work

### ISSUE THREAD

**Issue by YusukeIwaki** [YusukeIwaki/playwright-ruby-client#211]
### Step To Reproduce / Observed behavior

```rb
require 'playwright'

Playwright.create(playwright_cli_executable_path: './node_modules/.bin/playwright') do |playwright|
  devices = playwright.android.devices
  devices.each do |device|
    puts device.model
  end
  devices.map(&:close)
end
```

```
$ bundle exec ruby main.rb 
Traceback (most recent call last):
	12: from main.rb:3:in `<main>'
	11: from /Users/yusuke-iwaki/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/playwright-ruby-client-1.20.1/lib/playwright.rb:79:in `create'
	10: from main.rb:4:in `block in <main>'
	 9: from /Users/yusuke-iwaki/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/playwright-ruby-client-1.20.1/lib/playwright_api/android.rb:30:in `devices'
	 8: from /Users/yusuke-iwaki/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/playwright-ruby-client-1.20.1/lib/playwright/channel_owners/android.rb:8:in `devices'
	 7: from /Users/yusuke-iwaki/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/playwright-ruby-client-1.20.1/lib/playwright/channel.rb:20:in `send_message_to_server'
	 6: from /Users/yusuke-iwaki/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/playwright-ruby-client-1.20.1/lib/playwright/channel.rb:33:in `send_message_to_server_result'
	 5: from /Users/yusuke-iwaki/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/playwright-ruby-client-1.20.1/lib/playwright/channel.rb:67:in `with_logging'
	 4: from /Users/yusuke-iwaki/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/playwright-ruby-client-1.20.1/lib/playwright/channel.rb:34:in `block in send_message_to_server_result'
	 3: from /Users/yusuke-iwaki/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/playwright-ruby-client-1.20.1/lib/playwright/connection.rb:77:in `send_message_to_server'
	 2: from /Users/yusuke-iwaki/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/promises.rb:1471:in `value!'
	 1: from /Users/yusuke-iwaki/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/promises.rb:1257:in `wait_until_resolved!'
/Users/yusuke-iwaki/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/promises.rb:1257:in `raise': Error: port: expected number, got object (Playwright::Error)
```

### Expected behavior

It works

### Environment

Paste the output of `ruby --version`

**Comment by YusukeIwaki** [comment]
```
module Playwright
  define_channel_owner :Android do
    private def after_initialize
      @timeout_settings = TimeoutSettings.new
    end

    def devices(port: nil)
      resp = @channel.send_message_to_server('devices', port: port)
      resp.map { |device| ChannelOwners::AndroidDevice.from(device) }
    end
  end
end
```

This sends `port: nil` actually.
It is expected to send nothing.

**Comment by YusukeIwaki** [comment]
Also AndroidDevice#tree is already removed in Playwright 1.9.0. It doesn't work now.
