### ISSUE TITLE
Crash: Missing type BrowserContext

### ISSUE THREAD

**Issue by davidsf** [YusukeIwaki/playwright-ruby-client#217]
### Step To Reproduce / Observed behavior

Using playwright-ruby-client with capybara-playwright-driver. It crash with:

```
#<Thread:0x000055b12519e6b0@/usr/local/rvm/gems/ruby-2.6.10/gems/playwright-ruby-client-1.23.0/lib/playwright/transport.rb:52 run> terminated with exception (report_on_exception is true):
/usr/local/rvm/gems/ruby-2.6.10/gems/playwright-ruby-client-1.23.0/lib/playwright/connection.rb:218:in `rescue in create_remote_object': Missing type BrowserContext (RuntimeError)
	from /usr/local/rvm/gems/ruby-2.6.10/gems/playwright-ruby-client-1.23.0/lib/playwright/connection.rb:210:in `create_remote_object'
	from /usr/local/rvm/gems/ruby-2.6.10/gems/playwright-ruby-client-1.23.0/lib/playwright/connection.rb:132:in `dispatch'
	from /usr/local/rvm/gems/ruby-2.6.10/gems/playwright-ruby-client-1.23.0/lib/playwright/connection.rb:11:in `block in initialize'
	from /usr/local/rvm/gems/ruby-2.6.10/gems/playwright-ruby-client-1.23.0/lib/playwright/transport.rb:82:in `handle_stdout'
	from /usr/local/rvm/gems/ruby-2.6.10/gems/playwright-ruby-client-1.23.0/lib/playwright/transport.rb:52:in `block in async_run'
/usr/local/rvm/gems/ruby-2.6.10/gems/playwright-ruby-client-1.23.0/lib/playwright/channel_owner.rb:6:in `from': undefined method `object' for nil:NilClass (NoMethodError)
	from /usr/local/rvm/gems/ruby-2.6.10/gems/playwright-ruby-client-1.23.0/lib/playwright/channel_owners/browser_context.rb:21:in `after_initialize'
	from /usr/local/rvm/gems/ruby-2.6.10/gems/playwright-ruby-client-1.23.0/lib/playwright/channel_owner.rb:40:in `initialize'
	from /usr/local/rvm/gems/ruby-2.6.10/gems/playwright-ruby-client-1.23.0/lib/playwright/connection.rb:211:in `new'
	from /usr/local/rvm/gems/ruby-2.6.10/gems/playwright-ruby-client-1.23.0/lib/playwright/connection.rb:211:in `create_remote_object'
	from /usr/local/rvm/gems/ruby-2.6.10/gems/playwright-ruby-client-1.23.0/lib/playwright/connection.rb:132:in `dispatch'
	from /usr/local/rvm/gems/ruby-2.6.10/gems/playwright-ruby-client-1.23.0/lib/playwright/connection.rb:11:in `block in initialize'
	from /usr/local/rvm/gems/ruby-2.6.10/gems/playwright-ruby-client-1.23.0/lib/playwright/transport.rb:82:in `handle_stdout'
	from /usr/local/rvm/gems/ruby-2.6.10/gems/playwright-ruby-client-1.23.0/lib/playwright/transport.rb:52:in `block in async_run'
```
Maybe the gem needs a specific version of playwright  (just guessing) ? 

### Expected behavior

Run the test normally :)

### Environment
```
root@2887a861369a:/app# ruby --version
ruby 2.6.10p210 (2022-04-12 revision 67958) [x86_64-linux]
```

Thanks!

**Comment by davidsf** [comment]
As I mention, is for the version of playwright, npx install the last one (1.25).

Installing the correct versión with: `npm install @playwright/test@1.23.4` fixes de issue.

Sorry for the noise.
