### ISSUE TITLE
wait_for_load_state(state: "networkidle")

### ISSUE THREAD

**Issue by dsisnero** [YusukeIwaki/playwright-ruby-client#243]
### Step To Reproduce / Observed behavior

`page.wait_for_load_state(state: 'networkidle')`

```
f:\programming\source\repos\git\dsisnero\scrapers\cwp_scraper>ruby lib\cwp_scraper.rb
f:/windows/tools/ruby/Ruby3.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.0/lib/concurrent-ruby/
concurrent/promises.rb:1258:in `raise': Navigating frame was detached! (Playwright::FrameAlreadyD
etachedError)
        from f:/windows/tools/ruby/Ruby3.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.0/lib/con
current-ruby/concurrent/promises.rb:1258:in `wait_until_resolved!'
        from f:/windows/tools/ruby/Ruby3.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.0/lib/con
current-ruby/concurrent/promises.rb:1472:in `value!'
        from f:/windows/tools/ruby/Ruby3.2/lib/ruby/gems/3.2.0/gems/playwright-ruby-client-1.30.0
/lib/playwright/channel_owners/frame.rb:142:in `wait_for_load_state'
        from f:/windows/tools/ruby/Ruby3.2/lib/ruby/gems/3.2.0/gems/playwright-ruby-client-1.30.0
/lib/playwright/channel_owners/page.rb:343:in `wait_for_load_state'
        from f:/windows/tools/ruby/Ruby3.2/lib/ruby/gems/3.2.0/gems/playwright-ruby-client-1.30.0
/lib/playwright_api/page.rb:1479:in `wait_for_load_state'
        from lib/cwp_scraper.rb:40:in `block (2 levels) in <main>'
        from f:/windows/tools/ruby/Ruby3.2/lib/ruby/gems/3.2.0/gems/playwright-ruby-client-1.30.0
/lib/playwright/playwright_api.rb:121:in `block in wrap_block_call'
        from f:/windows/tools/ruby/Ruby3.2/lib/ruby/gems/3.2.0/gems/playwright-ruby-client-1.30.0
/lib/playwright/channel_owners/browser_type.rb:20:in `launch'
        from f:/windows/tools/ruby/Ruby3.2/lib/ruby/gems/3.2.0/gems/playwright-ruby-client-1.30.0
/lib/playwright_api/browser_type.rb:104:in `launch'
        from lib/cwp_scraper.rb:25:in `block in <main>'
        from f:/windows/tools/ruby/Ruby3.2/lib/ruby/gems/3.2.0/gems/playwright-ruby-client-1.30.0
/lib/playwright.rb:96:in `create'
        from lib/cwp_scraper.rb:7:in `<main>'

```
### Expected behavior
non error

### Environment

Paste the output of `ruby --version`

`f:\programming\source\repos\git\dsisnero\scrapers\cwp_scraper>ruby --version`
ruby 3.2.0 (2022-12-25 revision a528908271) [x64-mingw-ucrt]

**Comment by YusukeIwaki** [comment]
I tried the code below and no error is raised.

```ruby
      page.goto('https://playwright.dev/')
      page.wait_for_load_state(state: 'networkidle')
```

@dsisnero Could you provide an example code for reproducing this issue?

**Comment by timtait** [comment]
I've managed to replicate this, it seems to happen on sites with a load of ajax requests firing around in the background
```
require 'playwright'

Playwright.create(playwright_cli_executable_path: './node_modules/.bin/playwright') do |playwright|
  playwright.chromium.launch(headless: false) do |browser|
    page = browser.new_page
    page.goto('https://youtube.com')
   
    page.wait_for_load_state(state: 'networkidle')
   
    res = page.inner_text(:body)
    puts res
    return
  end
end
```

```
/test/.bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/promises.rb:1258:in `raise': Navigating frame was detached! (Playwright::FrameAlreadyDetachedError)
        from /test/.bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/promises.rb:1258:in `wait_until_resolved!'
        from /test/.bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/promises.rb:1472:in `value!'
        from /test/.bundle/ruby/3.2.0/gems/playwright-ruby-client-1.36.0/lib/playwright/channel_owners/frame.rb:142:in `wait_for_load_state'
        from /test/.bundle/ruby/3.2.0/gems/playwright-ruby-client-1.36.0/lib/playwright/channel_owners/page.rb:333:in `wait_for_load_state'
        from /test/.bundle/ruby/3.2.0/gems/playwright-ruby-client-1.36.0/lib/playwright_api/page.rb:1493:in `wait_for_load_state'
        from test.rb:15:in `block (2 levels) in <main>'
        from /test/.bundle/ruby/3.2.0/gems/playwright-ruby-client-1.36.0/lib/playwright/playwright_api.rb:121:in `block in wrap_block_call'
        from /test/.bundle/ruby/3.2.0/gems/playwright-ruby-client-1.36.0/lib/playwright/channel_owners/browser_type.rb:20:in `launch'
        from /test/.bundle/ruby/3.2.0/gems/playwright-ruby-client-1.36.0/lib/playwright_api/browser_type.rb:104:in `launch'
        from test.rb:5:in `block in <main>'
        from /test/.bundle/ruby/3.2.0/gems/playwright-ruby-client-1.36.0/lib/playwright.rb:96:in `create'
        from test.rb:4:in `<main>'
        ```
