### ISSUE TITLE
NoMethodError when enabling on_save_trace with Playwright in server mode for Rails System Test

### ISSUE THREAD

**Issue by mizoR** [YusukeIwaki/playwright-ruby-client#307]
Hi there, thanks for this great gem—it's been really helpful!

### Usecase / What to achieve

 I am running system tests for a Rails application using Playwright in server mode. I want to enable on_save_trace to collect tracing information for debugging and performance analysis.

### Question

I'm using Playwright in server mode to run System tests in a Rails environment. When I enable on_save_trace, I encounter the following error:

```
/usr/local/bundle/gems/playwright-ruby-client-1.47.0/lib/playwright/connection.rb:113:in `block in async_send_message_to_server': undefined method `add_stack_to_tracing_no_reply' for nil (NoMethodError)

          @local_utils.add_stack_to_tracing_no_reply(id, frames)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        from /usr/local/bundle/gems/playwright-ruby-client-1.47.0/lib/playwright/connection.rb:133:in `with_generated_id'
        from /usr/local/bundle/gems/playwright-ruby-client-1.47.0/lib/playwright/connection.rb:80:in `async_send_message_to_server'
        from /usr/local/bundle/gems/playwright-ruby-client-1.47.0/lib/playwright/connection.rb:121:in `send_message_to_server'
        from /usr/local/bundle/gems/playwright-ruby-client-1.47.0/lib/playwright/channel.rb:35:in `block in send_message_to_server_result'
        from /usr/local/bundle/gems/playwright-ruby-client-1.47.0/lib/playwright/channel.rb:67:in `with_logging'
        from /usr/local/bundle/gems/playwright-ruby-client-1.47.0/lib/playwright/channel.rb:34:in `send_message_to_server_result'
        from /usr/local/bundle/gems/playwright-ruby-client-1.47.0/lib/playwright/channel.rb:20:in `send_message_to_server'
        from /usr/local/bundle/gems/playwright-ruby-client-1.47.0/lib/playwright/channel_owners/browser.rb:75:in `close'
        from /usr/local/bundle/gems/playwright-ruby-client-1.47.0/lib/playwright_api/browser.rb:37:in `close'
        from /usr/local/bundle/gems/capybara-playwright-driver-0.5.2/lib/capybara/playwright/driver.rb:56:in `quit'
        from /usr/local/bundle/gems/capybara-playwright-driver-0.5.2/lib/capybara/playwright/driver.rb:48:in `block in create_playwright_browser'
/usr/local/bundle/gems/rspec-core-3.13.1/lib/rspec/core/runner.rb:46:in `exit': exit (SystemExit)
        from /usr/local/bundle/gems/rspec-core-3.13.1/lib/rspec/core/runner.rb:46:in `invoke'
        from /usr/local/bundle/gems/rspec-core-3.13.1/exe/rspec:4:in `<top (required)>'
        from bin/rspec:27:in `load'
        from bin/rspec:27:in `<main>'
```

Here is a Rails application that reproduces the problem.
https://github.com/mizoR/capybara-playwright-example

I'm not sure if on_save_trace is fully supported in server mode or if this is a bug. Could someone clarify if this functionality is expected to work in server mode, or if there might be a missing configuration or an alternative approach?

Thank you for your support and for all your hard work on Playwright.

**Comment by YusukeIwaki** [comment]
It seems LocalUtils is available only when playwright driver is executed on the local.

Playwright server-mode is not officially used in Python, Java, C# drivers.
They use `BrowserType#connect` instead and BrowserType internally has local driver connection.

```
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    # browser = p.chromium.launch(channel="chrome")
    browser = p.chromium.connect('ws://localhost:9999/chromium')
    try:
        context = browser.new_context()
        context.tracing.start(screenshots=True, snapshots=True)
        page = context.new_page()
        page.goto("https://github.com/YusukeIwaki")
        page.screenshot(path="YusukeIwaki.png")
        context.tracing.stop(path="trace.zip")
    finally:
        browser.close()
```

On the other hand, Ruby driver does not use BrowserType for connecting to the Playwright server or Browser server.
This is the root cause of this issue...

```
#Playwright.create(playwright_cli_executable_path: './node_modules/.bin/playwright') do |playwright|
Playwright.connect_to_browser_server('ws://localhost:9999/chromium') do |browser|
  # playwright.chromium.launch(headless: false) do |browser|
    context = browser.new_context
    context.tracing.start(screenshots: true, snapshots: true)
    page = context.new_page
    page.goto('https://github.com/YusukeIwaki')
    page.screenshot(path: './YusukeIwaki.png')
    context.tracing.stop(path: './trace.zip')
    context.close
  # end
end
```

**Comment by mizoR** [comment]
Thank you for your explanation!

From your response, I understand that LocalUtils is only available when the Playwright driver is run locally, and that server mode is not officially supported for the Python, Java, and C# drivers. This probably means that it might also be difficult to fully support Ruby drivers in server mode, right?

I was hoping to avoid installing Playwright in the application container, but given the current limitations, if tracing is important, I might need to consider switching to a local connection instead of using the server mode.

Thanks again for your support and the helpful information! ✨
