### ISSUE TITLE
uninitialized constant Playwright::ChannelOwners::Worker (NameError)

### ISSUE THREAD

**Issue by Overload119** [YusukeIwaki/playwright-ruby-client#96]
### Step To Reproduce / Observed behavior

1. spring rails c
2. `Playwright::ChannelOwners.const_get('Worker')`

<details>
<summary>Stack Trace</summary>

```
 #<Thread:0x00007fa4f9bb30f0 /Users/amirsharif/.rvm/gems/ruby-2.7.2/gems/playwright-ruby-client-0.6.0/lib/playwright/transport.rb:53 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	5: from /Users/amirsharif/.rvm/gems/ruby-2.7.2/gems/playwright-ruby-client-0.6.0/lib/playwright/transport.rb:53:in `block in async_run'
	4: from /Users/amirsharif/.rvm/gems/ruby-2.7.2/gems/playwright-ruby-client-0.6.0/lib/playwright/transport.rb:71:in `handle_stdout'
	3: from /Users/amirsharif/.rvm/gems/ruby-2.7.2/gems/playwright-ruby-client-0.6.0/lib/playwright/connection.rb:13:in `block in initialize'
	2: from /Users/amirsharif/.rvm/gems/ruby-2.7.2/gems/playwright-ruby-client-0.6.0/lib/playwright/connection.rb:126:in `dispatch'
	1: from /Users/amirsharif/.rvm/gems/ruby-2.7.2/gems/playwright-ruby-client-0.6.0/lib/playwright/connection.rb:202:in `create_remote_object'
/Users/amirsharif/.rvm/gems/ruby-2.7.2/gems/playwright-ruby-client-0.6.0/lib/playwright/connection.rb:202:in `const_get': uninitialized constant Playwright::ChannelOwners::Worker (NameError)
Did you mean?  Playwright::Worker
	5: from /Users/amirsharif/.rvm/gems/ruby-2.7.2/gems/playwright-ruby-client-0.6.0/lib/playwright/transport.rb:53:in `block in async_run'
	4: from /Users/amirsharif/.rvm/gems/ruby-2.7.2/gems/playwright-ruby-client-0.6.0/lib/playwright/transport.rb:71:in `handle_stdout'
	3: from /Users/amirsharif/.rvm/gems/ruby-2.7.2/gems/playwright-ruby-client-0.6.0/lib/playwright/connection.rb:13:in `block in initialize'
	2: from /Users/amirsharif/.rvm/gems/ruby-2.7.2/gems/playwright-ruby-client-0.6.0/lib/playwright/connection.rb:126:in `dispatch'
	1: from /Users/amirsharif/.rvm/gems/ruby-2.7.2/gems/playwright-ruby-client-0.6.0/lib/playwright/connection.rb:201:in `create_remote_object'
/Users/amirsharif/.rvm/gems/ruby-2.7.2/gems/playwright-ruby-client-0.6.0/lib/playwright/connection.rb:209:in `rescue in create_remote_object': Missing type Worker (RuntimeError)
```

</details>

### Expected behavior

No error. 

### Environment

```
ruby 2.7.2p137
Rails 6.1.3.2
```

**Comment by Overload119** [comment]
It seems I'm able to fix this in the console by running this:

`Playwright::ChannelOwners.const_set('Worker', Class.new(Playwright::ChannelOwner))`

This leads to another error though down the line:

```
 #<Thread:0x00007fa4eb81ee70 /Users/amirsharif/.rvm/gems/ruby-2.7.2/gems/playwright-ruby-client-0.6.0/lib/playwright/transport.rb:53 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	9: from /Users/amirsharif/.rvm/gems/ruby-2.7.2/gems/playwright-ruby-client-0.6.0/lib/playwright/transport.rb:53:in `block in async_run'
	8: from /Users/amirsharif/.rvm/gems/ruby-2.7.2/gems/playwright-ruby-client-0.6.0/lib/playwright/transport.rb:71:in `handle_stdout'
	7: from /Users/amirsharif/.rvm/gems/ruby-2.7.2/gems/playwright-ruby-client-0.6.0/lib/playwright/connection.rb:13:in `block in initialize'
	6: from /Users/amirsharif/.rvm/gems/ruby-2.7.2/gems/playwright-ruby-client-0.6.0/lib/playwright/connection.rb:148:in `dispatch'
	5: from /Users/amirsharif/.rvm/gems/ruby-2.7.2/gems/playwright-ruby-client-0.6.0/lib/playwright/event_emitter.rb:40:in `emit'
	4: from /Users/amirsharif/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/set.rb:328:in `each'
	3: from /Users/amirsharif/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/set.rb:328:in `each_key'
	2: from /Users/amirsharif/.rvm/gems/ruby-2.7.2/gems/playwright-ruby-client-0.6.0/lib/playwright/event_emitter.rb:41:in `block in emit'
	1: from /Users/amirsharif/.rvm/gems/ruby-2.7.2/gems/playwright-ruby-client-0.6.0/lib/playwright/event_emitter.rb:8:in `call'
/Users/amirsharif/.rvm/gems/ruby-2.7.2/gems/playwright-ruby-client-0.6.0/lib/playwright/channel_owners/page.rb:67:in `block in after_initialize': undefined method `on_worker' for #<page@ef39ab268038eef4ecf287d249ce437a> (NoMethodError)
```

**Comment by Overload119** [comment]
This only happens for some pages, fwiw. 

Here is one: `https://www.linkedin.com/in/railsonmaui/`

**Comment by YusukeIwaki** [comment]
@Overload119 Thank you for your detailed report.
I found a similar issue in another web site, and fixed in 0.6.2.
Could you try the latest veision of this library?

**Comment by goldenking0412** [comment]
I have same issue and already on 0.6.2
Seems like it's getting when query_selector or something else.
I can not catch exception using rescue.
Can you please check?

**Comment by YusukeIwaki** [comment]
`page.goto('https://keycode.info/')` would causes the same error on 0.6.0.

```
#<Thread:0x00007f84ddd3e438 /Users/yusuke-iwaki/src/github.com/YusukeIwaki/playwright-ruby-client/lib/playwright/transport.rb:53 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	5: from /Users/yusuke-iwaki/src/github.com/YusukeIwaki/playwright-ruby-client/lib/playwright/transport.rb:53:in `block in async_run'
	4: from /Users/yusuke-iwaki/src/github.com/YusukeIwaki/playwright-ruby-client/lib/playwright/transport.rb:71:in `handle_stdout'
	3: from /Users/yusuke-iwaki/src/github.com/YusukeIwaki/playwright-ruby-client/lib/playwright/connection.rb:13:in `block in initialize'
	2: from /Users/yusuke-iwaki/src/github.com/YusukeIwaki/playwright-ruby-client/lib/playwright/connection.rb:126:in `dispatch'
	1: from /Users/yusuke-iwaki/src/github.com/YusukeIwaki/playwright-ruby-client/lib/playwright/connection.rb:202:in `create_remote_object'
/Users/yusuke-iwaki/src/github.com/YusukeIwaki/playwright-ruby-client/lib/playwright/connection.rb:202:in `const_get': uninitialized constant Playwright::ChannelOwners::Worker (NameError)
Did you mean?  Playwright::Worker
	5: from /Users/yusuke-iwaki/src/github.com/YusukeIwaki/playwright-ruby-client/lib/playwright/transport.rb:53:in `block in async_run'
	4: from /Users/yusuke-iwaki/src/github.com/YusukeIwaki/playwright-ruby-client/lib/playwright/transport.rb:71:in `handle_stdout'
	3: from /Users/yusuke-iwaki/src/github.com/YusukeIwaki/playwright-ruby-client/lib/playwright/connection.rb:13:in `block in initialize'
	2: from /Users/yusuke-iwaki/src/github.com/YusukeIwaki/playwright-ruby-client/lib/playwright/connection.rb:126:in `dispatch'
	1: from /Users/yusuke-iwaki/src/github.com/YusukeIwaki/playwright-ruby-client/lib/playwright/connection.rb:201:in `create_remote_object'
/Users/yusuke-iwaki/src/github.com/YusukeIwaki/playwright-ruby-client/lib/playwright/connection.rb:209:in `rescue in create_remote_object': Missing type Worker (RuntimeError)
```

This problem is fixed on 0.6.2

**Comment by goldenking0412** [comment]
```
#<Thread:0x00000000062e7dd0@/home/user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/playwright-ruby-client-0.6.2/lib/playwright/transport.rb:53 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	9: from /home/user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/playwright-ruby-client-0.6.2/lib/playwright/transport.rb:53:in `block in async_run'
	8: from /home/user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/playwright-ruby-client-0.6.2/lib/playwright/transport.rb:71:in `handle_stdout'
	7: from /home/user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/playwright-ruby-client-0.6.2/lib/playwright/connection.rb:13:in `block in initialize'
	6: from /home/user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/playwright-ruby-client-0.6.2/lib/playwright/connection.rb:148:in `dispatch'
	5: from /home/user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/playwright-ruby-client-0.6.2/lib/playwright/event_emitter.rb:40:in `emit'
	4: from /home/user/.rbenv/versions/2.6.6/lib/ruby/2.6.0/set.rb:338:in `each'
	3: from /home/user/.rbenv/versions/2.6.6/lib/ruby/2.6.0/set.rb:338:in `each_key'
	2: from /home/user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/playwright-ruby-client-0.6.2/lib/playwright/event_emitter.rb:41:in `block in emit'
	1: from /home/user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/playwright-ruby-client-0.6.2/lib/playwright/event_emitter.rb:8:in `call'
/home/user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/playwright-ruby-client-0.6.2/lib/playwright/channel_owners/page.rb:68:in `block in after_initialize': undefined method `on_worker' for #<page@0f3cc6c8380f216c939b8d1c3c30433a> (NoMethodError)
```

This is what I am getting when do query_selector or query_selector_all or wait_for_selector

**Comment by YusukeIwaki** [comment]
Oh, thank you for providing stack trace.
Page doesn't have on_worker, because the feature for handling ServiceWorker is not implemented at this point.
I will remove the call of on_worker.

**Comment by goldenking0412** [comment]
Let me know once this issue is fixed

**Comment by YusukeIwaki** [comment]
@Overload119 @goldenking0412  playwright-ruby-client 0.6.3 includes a fix of this issue. Thank you.
